"use client";

import Link from "next/link";
import Sidebar from "../components/Sidebar";

const reports = [
  {
    title: "Marketing Strategies",
    description: "View every AI marketing strategy you've created.",
    icon: "📈",
    href: "/history",
    color: "from-blue-600 to-indigo-600",
  },
  {
    title: "Ad Campaigns",
    description: "Manage all AI-generated Facebook and Google ads.",
    icon: "📢",
    href: "/ads/history",
    color: "from-green-600 to-emerald-600",
  },
  {
    title: "Health Reports",
    description: "Review every marketing health score.",
    icon: "❤️",
    href: "/health/history",
    color: "from-red-500 to-pink-500",
  },
  {
    title: "Website Audits",
    description: "See every website audit you've generated.",
    icon: "🌐",
    href: "/audit/history",
    color: "from-purple-600 to-violet-600",
  },
  {
    title: "Social Media Plans",
    description: "Browse all AI-generated social calendars.",
    icon: "📱",
    href: "/social/history",
    color: "from-orange-500 to-amber-500",
  },
];

export default function ReportsPage() {
  return (
    <div className="flex min-h-screen bg-gray-100">
      <Sidebar />

      <main className="flex-1 p-8">
        <h1 className="text-5xl font-black text-blue-600">
          Report Center
        </h1>

        <p className="text-gray-500 mt-3 mb-10 text-lg">
          Access every report generated by Apex AI.
        </p>

        <div className="grid lg:grid-cols-2 gap-8">
          {reports.map((report) => (
            <Link key={report.title} href={report.href}>
              <div className="bg-white rounded-3xl shadow-xl hover:shadow-2xl transition-all duration-300 cursor-pointer overflow-hidden">

                <div
                  className={`bg-gradient-to-r ${report.color} p-6 text-white`}
                >
                  <div className="text-5xl mb-3">
                    {report.icon}
                  </div>

                  <h2 className="text-3xl font-black">
                    {report.title}
                  </h2>
                </div>

                <div className="p-6">
                  <p className="text-gray-600">
                    {report.description}
                  </p>

                  <button className="mt-6 bg-blue-600 hover:bg-blue-700 text-white px-5 py-3 rounded-xl font-bold">
                    View Reports →
                  </button>
                </div>

              </div>
            </Link>
          ))}
        </div>
      </main>
    </div>
  );
}